#!/usr/bin/env python
#
# git-sba

import sys
from fnmatch import fnmatchcase
from subprocess import Popen, PIPE

class CalledProcessError(Exception):
    pass

def check_output(*args, **kwargs):
    kwargs['stdout'] = PIPE
    p = Popen(*args, **kwargs)
    out, err = p.communicate()
    code = p.wait()
    if code != 0:
        raise CalledProcessError(code, args[0])
    return out

def git_call(cmd_args, *args, **kwargs):
    cmd = ['git'] + cmd_args
    return check_output(cmd, *args, **kwargs)

def git_branches():
    branchoutput = git_call(['branch', '--no-color', '-av'])
    return [b[2:].strip().split(None, 2) for b in branchoutput.splitlines()]

config_items = (
    'hide',
    'alwaysshow'
)

def git_config(item, default=''):
    try:
        val = git_call(['config', item])
    except CalledProcessError, e:
        if e.args[0] == 1:
            return default
        raise
    return val

def git_sba_config():
    conf = {}
    for item in config_items:
        conf[item] = git_config('sba.%s' % item).strip()
    return conf

def sort_branches(branches):
    remote = []
    local = []
    for bname, commit, desc in branches:
        (remote if bname.startswith('remotes/') else local).append((bname, commit, desc))
    return remote, local

def remove_hidden(hidelist, branches):
    hides = hidelist.split(';')

    result = []
    for bname, commit, desc in branches:
        if any(fnmatchcase(bname, patt) for patt in hides):
            continue
        result.append((bname, commit, desc))
    return result

def remove_links(branches):
    return [(b, c, d) for (b, c, d) in branches if c != '->']

def find_matching_remotes(config, local, remote):
    wanted_remotes = []
    remoteset = set()
    for bname, commit, desc in local:
        for rbname, rcommit, rdesc in remote:
            if fnmatchcase(rbname, 'remotes/*/%s' % bname):
                if rbname not in remoteset:
                    wanted_remotes.append((rbname, rcommit, rdesc))
                    remoteset.add(rbname)
    extra_list = config['alwaysshow'].split(';')
    for patt in extra_list:
        for rbname, rcommit, rdesc in remote:
            if rbname not in remoteset and fnmatchcase(rbname, patt):
                wanted_remotes.append((rbname, rcommit, rdesc))
                remoteset.add(rbname)
    return local + wanted_remotes

def determine_showlist(config, local, remote):
    local = remove_hidden(config['hide'], local)
    remote = remove_hidden(config['hide'], remote)
    local = remove_links(local)
    remote = remove_links(remote)
    showlist = local + find_matching_remotes(config, local, remote)
    return [b[0] for b in showlist]

def showlist():
    branches = git_branches()
    remote, local = sort_branches(branches)
    config = git_sba_config()
    return determine_showlist(config, local, remote)

def main(args):
    g = Popen(['git', 'show-branch', '--color=always'] + showlist(), stdout=PIPE)
    git_pager = git_config('core.pager', 'less -FSRX')
    less = Popen(git_pager, shell=True, stdin=g.stdout)
    g.wait()
    return less.wait()

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
